name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"  # Actualiza diariamente a medianoche UTC
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: azufrecs
          outputs: out/snake.svg
          snake_color: "#4CC9F0"  # Azul el칠ctrico
          empty_color: "#F8F9FA"  # Gris claro para fondo
          snake_size: "large"
          snake_type: "greedy"    # Mordiscos m치s agresivos
          rect_size: 12           # Cuadritos m치s grandes
          gap: 1                  # Menos espacio entre cuadros
          circles: true           # Forma circular moderna
          commit_frequency: "daily" # M치xima frecuencia

      - name: Boost Visual Impact
        run: |
          # Aumenta opacidad y tama침o (efecto m치s visible)
          sed -i 's/"fill-opacity": 0.1/"fill-opacity": 0.6/g' out/snake.svg
          sed -i 's/"width": 10/"width": 16/g' out/snake.svg
          sed -i 's/"stroke-width": 1/"stroke-width": 2/g' out/snake.svg

      - name: Push to Output Branch
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            try {
              execSync('git checkout --orphan output');
              execSync('git rm -rf .');
              fs.copyFileSync('out/snake.svg', 'github-contribution-grid-snake.svg');
              
              # Crea un README.md adicional para el branch
              fs.writeFileSync('README.md', '# Snake Animation\n\n![Snake](github-contribution-grid-snake.svg)');
              
              execSync('git add .');
              execSync('git config user.name "GitHub Snake Bot"');
              execSync('git config user.email "snake-bot@users.noreply.github.com"');
              execSync('git commit -m "游댃 Updated snake animation $(date +\'%Y-%m-%d\')"');
              execSync('git push origin output --force');
            } catch (error) {
              console.error(error);
              core.setFailed(error.message);
            }
