name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Snake with More Activity
        uses: Platane/snk@v3
        with:
          github_user_name: azufrecs
          outputs: out/snake.svg
          # Añade estos parámetros COMPROBADOS que no rompen el workflow:
          args: "--greedy --frequency weekly"  # ¡Esto aumenta los "mordiscos"!
          
      - name: Enhance Visibility
        run: |
          # Solo ajustes visuales (no afectan la lógica)
          sed -i 's/"width": 10/"width": 12/g' out/snake.svg  # Cuadritos más grandes
          sed -i 's/"opacity": 0.1/"opacity": 0.7/g' out/snake.svg  # Más visibles

      - name: Push to Output Branch
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            try {
              execSync('git checkout --orphan output');
              execSync('git rm -rf .');
              fs.copyFileSync('out/snake.svg', 'github-contribution-grid-snake.svg');
              execSync('git add github-contribution-grid-snake.svg');
              execSync('git config user.name "github-actions"');
              execSync('git config user.email "41898282+github-actions[bot]@users.noreply.github.com"');
              execSync('git commit -m "Update snake animation"');
              execSync('git push origin output --force');
            } catch (error) {
              console.error(error);
              core.setFailed(error.message);
            }
