name: Generate Snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main

jobs:
  generate-snake:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
        
      - name: Generate Snake
        uses: Platane/snk@v3
        with:
          github_user_name: azufrecs
          outputs: out/snake.svg
          # Solo parámetros oficialmente soportados:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          args: "--user azufrecs --output out/snake.svg --color green --size large"

      - name: Enhance Visuals
        run: |
          # Modificación directa del SVG para mejor visibilidad
          sed -i 's/"width": 10/"width": 14/g' out/snake.svg
          sed -i 's/"height": 10/"height": 14/g' out/snake.svg
          sed -i 's/"fill-opacity": 0.1/"fill-opacity": 0.5/g' out/snake.svg

      - name: Push to Output Branch
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const { execSync } = require('child_process');
            try {
              execSync('git checkout --orphan output');
              execSync('git rm -rf .');
              fs.copyFileSync('out/snake.svg', 'github-contribution-grid-snake.svg');
              execSync('git add github-contribution-grid-snake.svg');
              execSync('git config user.name "GitHub Actions"');
              execSync('git config user.email "actions@github.com"');
              execSync('git commit -m "Update snake animation"');
              execSync('git push origin output --force');
            } catch (error) {
              console.error(error);
              core.setFailed(error.message);
            }
